#!/bin/bash
echo "=== QQ Bot Status ==="
echo "Process:"
ps aux | grep test_qq_echo_standalone | grep -v grep || echo "Not running"
echo ""
echo "Recent system logs (last 20 lines):"
journalctl -u python3 -n 20 --no-pager 2>/dev/null || echo "No journalctl logs"
echo ""
echo "To stop the bot: pkill -f test_qq_echo_standalone.py"
echo "To view live logs: journalctl -f | grep python"
